//! Key-output protection.
//!
//! Every found private key is encrypted to an **age (X25519) recipient** before
//! it ever touches disk or console, so a compromised mining box — or a leaked
//! `scanned_keys.txt` — yields only ciphertext. The matching secret identity
//! lives OFFLINE (generated by `nullforge-keygen`, decrypted by
//! `nullforge-decrypt`) and never runs on the mining host.
use std::str::FromStr;

use base64::prelude::{Engine as _, BASE64_STANDARD};
use ethers::utils::hex;

/// Where a found private key goes in the `scanned_keys.txt` key column.
pub enum KeySink {
    /// Secure default: encrypt to this age recipient, store `base64(age ciphertext)`.
    Encrypt(age::x25519::Recipient),
    /// INSECURE, explicit opt-in only (`--reveal`): store the raw hex private key.
    RevealPlaintext,
}

/// Parse an `age1...` recipient string.
pub fn parse_recipient(s: &str) -> Result<age::x25519::Recipient, String> {
    age::x25519::Recipient::from_str(s.trim())
        .map_err(|e| format!("invalid age recipient {s:?}: {e}"))
}

/// Resolve the key sink for a miner run.
///
/// `reveal == true` forces INSECURE plaintext output. Otherwise the recipient is
/// sourced, in order, from the `NULLFORGE_AGE_RECIPIENT` env var, then the first
/// `age1...` line of `age-recipient.txt` (written by `nullforge-keygen`). With
/// neither present this returns `Err`, so callers **fail closed** instead of
/// silently writing plaintext keys.
pub fn resolve_sink(reveal: bool) -> Result<KeySink, String> {
    if reveal {
        return Ok(KeySink::RevealPlaintext);
    }
    if let Ok(v) = std::env::var("NULLFORGE_AGE_RECIPIENT") {
        let v = v.trim();
        if !v.is_empty() {
            return Ok(KeySink::Encrypt(parse_recipient(v)?));
        }
    }
    if let Ok(contents) = std::fs::read_to_string("age-recipient.txt") {
        if let Some(line) = contents
            .lines()
            .map(str::trim)
            .find(|l| l.starts_with("age1"))
        {
            return Ok(KeySink::Encrypt(parse_recipient(line)?));
        }
    }
    Err(
        "no age recipient configured. Run `nullforge-keygen` (writes age-recipient.txt and \
         prints the secret to store OFFLINE), or set NULLFORGE_AGE_RECIPIENT=age1..., or pass \
         --reveal to write PLAINTEXT keys (INSECURE)."
            .to_string(),
    )
}

/// Encode a found private key for the key column.
/// Secure: `base64(age_encrypt(privkey))`. Reveal: raw hex (insecure).
pub fn encode_key_field(sink: &KeySink, privkey: &[u8; 32]) -> Result<String, String> {
    match sink {
        KeySink::RevealPlaintext => Ok(hex::encode(privkey)),
        KeySink::Encrypt(recipient) => {
            let ct =
                age::encrypt(recipient, privkey).map_err(|e| format!("age encrypt failed: {e}"))?;
            Ok(BASE64_STANDARD.encode(ct))
        }
    }
}

/// Offline recovery: `base64 -> age ciphertext -> plaintext` with a secret identity.
pub fn decrypt_key_field(identity: &age::x25519::Identity, field: &str) -> Result<Vec<u8>, String> {
    let ct = BASE64_STANDARD
        .decode(field.trim())
        .map_err(|e| format!("base64 decode failed: {e}"))?;
    age::decrypt(identity, &ct).map_err(|e| format!("age decrypt failed: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encrypt_then_decrypt_roundtrips_and_hides_plaintext() {
        // A test identity generated in-process (the miner would only ever hold
        // the public recipient; the secret stays offline in real use).
        let identity = age::x25519::Identity::generate();
        let recipient = identity.to_public();
        let sink = KeySink::Encrypt(recipient);

        let privkey: [u8; 32] = [0xAB; 32];
        let field = encode_key_field(&sink, &privkey).unwrap();

        // The plaintext hex key must NOT appear in the encoded field.
        assert!(
            !field.contains(&hex::encode(privkey)),
            "plaintext leaked: {field}"
        );

        // ...and it round-trips back to the exact key with the secret identity.
        let recovered = decrypt_key_field(&identity, &field).unwrap();
        assert_eq!(recovered, privkey.to_vec());
    }

    #[test]
    fn reveal_sink_is_plain_hex() {
        let privkey: [u8; 32] = [0x01; 32];
        let field = encode_key_field(&KeySink::RevealPlaintext, &privkey).unwrap();
        assert_eq!(field, hex::encode(privkey));
    }

    #[test]
    fn resolve_sink_reveal_flag_bypasses_recipient() {
        assert!(matches!(
            resolve_sink(true).unwrap(),
            KeySink::RevealPlaintext
        ));
    }
}
